language: node_js
sudo: false
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "time make travis.before_install"
install:
  - "time make install"
before_script:
  - "time make travis.before_script"
script:
  - "time make travis.script"
services:
  - docker
