language: generic
sudo: true
services:
  - docker
before_install: make travis.before_install
install: make travis.install
before_script: make travis.before_script
script: make travis.script
after_script: make travis.after_script
before_deploy: make travis.before_deploy
deploy:
  api_key:
    secure: cG6u88f7brUO9NrRjLzOKS+PIHd+TeGCUyyGMRJrw48nd+TUneeNhYc/NrCD9TfeGBIKAyDmyMf6eQkIX/TmAcSxxgGpevu3p2HS0pcyW9Rr6lOAaRfhIgh1gOav7es1BMQSFz9I40BJkUfDCjn2Ax17bjW0Wc2i3Omtb0gbBSE=
  provider: heroku
