mongodb:
  image: mongo:3.0.6
  # container_name: mongohost #not supported by docker-compose older than 1.4
  ports:
    - "27017"
web:
  build: ./
  dockerfile: dev.dockerfile
  volumes:
    - ./:/home/user/duelo:ro
  dns: 8.8.8.8
  ports:
    - "80:80"
  links:
    - mongodb:mongohost
  command: sh/web.proc
